// actions for User
export const FETCHING_USER_DATA = 'FETCHING_USER_DATA';
export const FETCHING_USER_DATA_SUCCESS = 'FETCHING_USER_DATA_SUCCESS';
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR';

// actions for Albums
export const FETCHING_ALBUM_DATA = 'FETCHING_ALBUM_DATA';
export const FETCHING_ALBUM_DATA_SUCCESS = 'FETCHING_ALBUM_DATA_SUCCESS';
export const FETCHING_ALBUM_ERROR = 'FETCHING_ALBUM_ERROR';

// actions for Photos
export const FETCHING_PHOTO_DATA = 'FETCHING_PHOTO_DATA';
export const FETCHING_PHOTO_DATA_SUCCESS = 'FETCHING_PHOTO_DATA_SUCCESS';
export const FETCHING_PHOTO_ERROR = 'FETCHING_PHOTO_ERROR';
